In [82]:
import numpy as np
import pandas as od
import matplotlib.pyplot as plt

%matplotlib inline

In [83]:
#download the file
#datasets retrieved from the machine learning repository at UCI.edu

breastCancer = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data", header= None)

In [84]:
#peak at the data
breastCancer.head()

0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [85]:
#write column names
breastCancer.columns = ["id_number","clump_thinkness","unit_cell_size", "unit_cell_shape",
                       "marg_adhesion","single_epith_cell_size","bare_nuclei","bland_chromatin",
                       "normal_nucleoli","mitoses","class"]

In [86]:
breastCancer.head()

id_number  clump_thinkness  unit_cell_size  unit_cell_shape  marg_adhesion  \
0    1000025                5               1                1              1   
1    1002945                5               4                4              5   
2    1015425                3               1                1              1   
3    1016277                6               8                8              1   
4    1017023                4               1                1              3   

   single_epith_cell_size bare_nuclei  bland_chromatin  normal_nucleoli  \
0                       2           1                3                1   
1                       7          10                3                2   
2                       2           2                3                1   
3                       3           4                3                7   
4                       2           1                3                1   

   mitoses  class  
0        1      2  
1        1      2  
2        1      2  
3        1      2  
4        1      2

In [87]:
#show summary
breastCancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   id_number               699 non-null    int64 
 1   clump_thinkness         699 non-null    int64 
 2   unit_cell_size          699 non-null    int64 
 3   unit_cell_shape         699 non-null    int64 
 4   marg_adhesion           699 non-null    int64 
 5   single_epith_cell_size  699 non-null    int64 
 6   bare_nuclei             699 non-null    object
 7   bland_chromatin         699 non-null    int64 
 8   normal_nucleoli         699 non-null    int64 
 9   mitoses                 699 non-null    int64 
 10  class                   699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [88]:
#replace all ? to NaN
breastCancer.bare_nuclei = breastCancer.bare_nuclei.replace("?", np.NaN)

In [89]:
#print out the columns with NaN values
print(breastCancer.isnull())

#count all values with NaN
breastCancer.isnull().values.sum()

     id_number  clump_thinkness  unit_cell_size  unit_cell_shape  \
0        False            False           False            False   
1        False            False           False            False   
2        False            False           False            False   
3        False            False           False            False   
4        False            False           False            False   
..         ...              ...             ...              ...   
694      False            False           False            False   
695      False            False           False            False   
696      False            False           False            False   
697      False            False           False            False   
698      False            False           False            False   

     marg_adhesion  single_epith_cell_size  bare_nuclei  bland_chromatin  \
0            False                   False        False            False   
1            False             

16

In [90]:
#calculate mode
#change values in NaN with value_counts()function; get a series containing counts of values


breastCancer.bare_nuclei = breastCancer.bare_nuclei.fillna(breastCancer.bare_nuclei.value_counts().index[0])


In [91]:
#changing column names into 0 and 1

breastCancer["cancer_ind"] = 0
breastCancer.loc[breastCancer["class"] == 4, "cancer_ind"] = 1  #boolean array

In [92]:
X_df = breastCancer.drop(["id_number","class","cancer_ind"], axis=1)
y = breastCancer.cancer_ind

In [93]:
from sklearn.preprocessing import StandardScaler

In [94]:
scaler = StandardScaler()

In [95]:
scaler.fit_transform(X_df)

array([[ 0.20693572, -0.69999505, -0.74329904, ..., -0.17966213,
        -0.61182504, -0.34391178],
       [ 0.20693572,  0.28384518,  0.2668747 , ..., -0.17966213,
        -0.28411186, -0.34391178],
       [-0.50386559, -0.69999505, -0.74329904, ..., -0.17966213,
        -0.61182504, -0.34391178],
       ...,
       [ 0.20693572,  2.25152563,  2.28722218, ...,  1.87236122,
         2.33759359,  0.23956962],
       [-0.14846494,  1.59563215,  0.94032386, ...,  2.69317056,
         1.02674087, -0.34391178],
       [-0.14846494,  1.59563215,  1.61377302, ...,  2.69317056,
         0.37131451, -0.34391178]])

In [96]:
X_scaled_df = scaler.fit_transform(X_df)

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled_df, y,
                                                    test_size=0.3, random_state=42)

In [99]:
#classifier
from sklearn.neighbors import KNeighborsClassifier

In [100]:
knn = KNeighborsClassifier(n_neighbors=3)

In [101]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [102]:
#import evaluation libraries
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score,roc_curve

In [103]:
#prediction
y_pred = knn.predict(X_test) 

In [104]:
accuracy_score(y_test, y_pred)

0.9761904761904762

In [105]:
confusion_matrix(y_test, y_pred)

array([[141,   2],
       [  3,  64]])

In [106]:
roc_auc_score(y_test, y_pred)

0.9706189333055005

In [110]:
from sklearn.model_selection import GridSearchCV


In [111]:
grid_search = GridSearchCV(knn, {"n_neighbors": [1,2,3,4,5]}, n_jobs = -1, cv = 7, scoring= "roc_auc") #cv= cross validation

In [112]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=7, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=3, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc', verbose=0)

In [113]:
grid_search.best_params_

{'n_neighbors': 4}

In [114]:
knn_best = grid_search.best_estimator_

In [115]:
y_pred= knn_best.predict(X_test)

In [116]:
accuracy_score(y_test, y_pred)

0.9619047619047619

In [117]:
confusion_matrix(y_test, y_pred)

array([[141,   2],
       [  6,  61]])

In [118]:
roc_auc_score(y_test, y_pred)

0.948230873604008